# Github Action to run terraform in this repo
name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
    terraform:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID:  ${{ secrets.Tejaswi_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.Tejaswi_SECRET_KEY }}
            AWS_DEFAULT_REGION: eu-west-1
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2


        - name: Set up Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.0.0
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
            

        - name: Initialize Terraform
          run: terraform init

        - name: Validate Terraform
          run: terraform validate

        - name: Format Terraform
          run: terraform fmt -check

        - name: Plan Terraform
          run: terraform plan

        - name: Apply Terraform
          run: terraform destroy -auto-approve -input=false